# Generated by Django 5.2.3 on 2025-07-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField(verbose_name='Région')),
                ('province', models.IntegerField(verbose_name='Province')),
                ('milieu', models.IntegerField(verbose_name='Milieu de résidence')),
                ('numero_menage_province', models.IntegerField(verbose_name='Numéro de ménage dans la province')),
                ('numero_ordre_menage', models.IntegerField(verbose_name="Numéro d'ordre dans le ménage")),
                ('lien_chef_menage', models.IntegerField(verbose_name='Lien avec le chef de ménage')),
                ('nationalite', models.IntegerField(verbose_name='Nationalité')),
                ('sexe', models.IntegerField(verbose_name='Sexe')),
                ('age_simple', models.IntegerField(blank=True, null=True, verbose_name='Âge simple')),
                ('age_quinquennal', models.IntegerField(blank=True, null=True, verbose_name='Âge quinquennal')),
                ('etat_matrimonial', models.IntegerField(verbose_name='État matrimonial')),
                ('enfants_vivants', models.IntegerField(blank=True, null=True, verbose_name='Enfants vivants')),
                ('enfants_decedes', models.IntegerField(blank=True, null=True, verbose_name='Enfants décédés')),
                ('naissances_vivantes_12m', models.IntegerField(blank=True, null=True, verbose_name='Naissances vivantes 12 derniers mois')),
                ('deces_12m', models.IntegerField(blank=True, null=True, verbose_name='Décès 12 derniers mois')),
                ('handicap_vision', models.IntegerField(blank=True, null=True, verbose_name='Handicap (Vision)')),
                ('handicap_audition', models.IntegerField(blank=True, null=True, verbose_name='Handicap (Audition)')),
                ('handicap_mobilite', models.IntegerField(blank=True, null=True, verbose_name='Handicap (Mobilité)')),
                ('handicap_memoire', models.IntegerField(blank=True, null=True, verbose_name='Handicap (Mémoire)')),
                ('handicap_entretien', models.IntegerField(blank=True, null=True, verbose_name='Handicap (Entretien)')),
                ('handicap_communication', models.IntegerField(blank=True, null=True, verbose_name='Handicap (Communication)')),
                ('situation_handicap', models.IntegerField(blank=True, null=True, verbose_name='Situation de handicap')),
                ('niveau_etudes', models.IntegerField(blank=True, null=True, verbose_name="Niveau d'études")),
                ('niveau_etudes_agriculture', models.IntegerField(blank=True, null=True, verbose_name="Niveau d'études agriculture")),
                ('secteur_enseignement', models.IntegerField(blank=True, null=True, verbose_name="Secteur d'enseignement")),
                ('scolarisation', models.IntegerField(blank=True, null=True, verbose_name='Scolarisation')),
                ('lieu_etudes', models.IntegerField(blank=True, null=True, verbose_name="Lieu d'études")),
                ('mode_transport_etudes', models.IntegerField(blank=True, null=True, verbose_name='Mode de transport études')),
                ('aptitude_lecture_ecriture', models.IntegerField(blank=True, null=True, verbose_name='Aptitude à lire et écrire')),
                ('langue_1', models.IntegerField(blank=True, null=True, verbose_name='1ère langue lue')),
                ('langue_2', models.IntegerField(blank=True, null=True, verbose_name='2ème langue lue')),
                ('langue_3', models.IntegerField(blank=True, null=True, verbose_name='3ème langue lue')),
                ('langue_locale_1', models.IntegerField(blank=True, null=True, verbose_name='1ère langue locale')),
                ('langue_locale_2', models.IntegerField(blank=True, null=True, verbose_name='2ème langue locale')),
                ('diplome_superieur_general', models.IntegerField(blank=True, null=True, verbose_name='Diplôme supérieur général')),
                ('diplome_general', models.IntegerField(blank=True, null=True, verbose_name='Diplôme général')),
                ('diplome_formation_professionnelle_superieur', models.IntegerField(blank=True, null=True, verbose_name='Diplôme FP supérieur')),
                ('diplome_formation_professionnelle_general', models.IntegerField(blank=True, null=True, verbose_name='Diplôme FP général')),
                ('diplome_formation_professionnelle_base', models.IntegerField(blank=True, null=True, verbose_name='Diplôme FP de base')),
                ('type_activite', models.IntegerField(blank=True, null=True, verbose_name="Type d'activité")),
                ('profession_superieur_general', models.IntegerField(blank=True, null=True, verbose_name='Profession supérieur général')),
                ('profession_general', models.IntegerField(blank=True, null=True, verbose_name='Profession général')),
                ('statut_professionnel', models.IntegerField(blank=True, null=True, verbose_name='Statut professionnel')),
                ('activite_economique_superieur', models.IntegerField(blank=True, null=True, verbose_name='Activité économique supérieur')),
                ('activite_economique_general', models.IntegerField(blank=True, null=True, verbose_name='Activité économique général')),
                ('lieu_travail', models.IntegerField(blank=True, null=True, verbose_name='Lieu de travail')),
                ('mode_transport_travail', models.IntegerField(blank=True, null=True, verbose_name='Mode de transport travail')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Individu',
                'verbose_name_plural': 'Individus',
                'db_table': 'recensement_individu',
                'indexes': [models.Index(fields=['region', 'province'], name='recensement_region_380111_idx'), models.Index(fields=['numero_menage_province'], name='recensement_numero__2cd0c8_idx'), models.Index(fields=['sexe'], name='recensement_sexe_6ca5c6_idx'), models.Index(fields=['age_simple'], name='recensement_age_sim_8e8126_idx'), models.Index(fields=['niveau_etudes'], name='recensement_niveau__57b6a5_idx'), models.Index(fields=['type_activite'], name='recensement_type_ac_b0290d_idx')],
                'unique_together': {('region', 'province', 'numero_menage_province', 'numero_ordre_menage')},
            },
        ),
    ]
