# Generated by Django 5.2.3 on 2025-07-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='individu',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='individu',
            name='etat_matrimonial',
            field=models.IntegerField(blank=True, null=True, verbose_name='État matrimonial'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='lien_chef_menage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lien avec le chef de ménage'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='milieu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Milieu de résidence'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='nationalite',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='numero_menage_province',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de ménage dans la province'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='numero_ordre_menage',
            field=models.IntegerField(blank=True, null=True, verbose_name="Numéro d'ordre dans le ménage"),
        ),
        migrations.AlterField(
            model_name='individu',
            name='province',
            field=models.IntegerField(blank=True, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='region',
            field=models.IntegerField(blank=True, null=True, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='sexe',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sexe'),
        ),
    ]
